### ISSUE TITLE
兄弟我试了，不能用啊

### ISSUE THREAD

**Issue by ccccmagicboy** [RigoLigoRLC/LC2KiCad#1]
能用吗？

**Comment by RigoLigoRLC** [comment]
最新的master上的代码正在进行重构，不要编译或更改。
最新版0.1.3的build可以使用，仅能转换PCB封装，具体操作见README。
如有其它问题，请提供命令行报错或/和出错文件。

**Comment by ccccmagicboy** [comment]
下面是一个简单的PCB库：
![90745324-0E78-4c0e-AFC1-939538DC2E22](https://user-images.githubusercontent.com/4132539/77380645-920ca880-6db6-11ea-874d-74f175f0f20a.png)
输出的结果如下：
![7FE732B9-7A6C-4823-8D59-1B0A058CC4C7](https://user-images.githubusercontent.com/4132539/77380647-93d66c00-6db6-11ea-9189-eb3d65d96553.png)

**Comment by RigoLigoRLC** [comment]
程序尚不支持实心填充，报错退出。删除实心填充、导线（铜层）后重试。

**Comment by RigoLigoRLC** [comment]
目前所有的Bug提交我都会新开一个issue，主项目正在重构，Bugfix会在重构时一并合并。

**Comment by RigoLigoRLC** [comment]
见[Issue 3](3)
