### ISSUE TITLE
file generated by lc2kicad causes error being loaded into kicad

### ISSUE THREAD

**Issue by Cricko25** [RigoLigoRLC/LC2KiCad#10]
[test_r.json.gz](https://github.com/RigoLigoRLC/LC2KiCad/files/5460764/test_r.json.gz)
The file attached is generated by lc2kicad; kicad fails to load it.

**Comment by RigoLigoRLC** [comment]
This footprint contains copper layer zones, and KiCad won't allow copper zones inside a footprint (except for keepout zones).

A warning message should be displayed while the zone being discarded.

This will not be fixed any time soon. Patch is scheduled for some time in the future.

**Comment by RigoLigoRLC** [comment]
Issue is resolved; however your file is gonna fail. It's a badly made resistor footprint, with ***fill region pads***.
