### ISSUE TITLE
Relicense to LGPL v2/v3 ONLY

### ISSUE THREAD

**Issue by RigoLigoRLC** [RigoLigoRLC/LC2KiCad#16]
I'm about to relicense this project, to LGPL v2 and v3 only, no change to later versions permitted.

By allowing "(at your option) any later version", the freedom of my project would be at the mercy of FSF.

If all contributors agree, I'll go for relicense in a pull request.

@BadLuckW 

@Lawrence-Link

**Comment by Lawrence-Link** [comment]
Surely. :P

**Comment by BadLuckW** [comment]
okay

**Comment by RigoLigoRLC** [comment]
Thanks guys. The license change will be made soon.
