### ISSUE TITLE
嘉立创EDA 元器件导出文件不是 .json 格式问题

### ISSUE THREAD

**Issue by chenhaimeng** [RigoLigoRLC/LC2KiCad#22]
你好，
如题；
测试器件连接：
https://item.szlcsc.com/76318.html
嘉立创EDA版本
版本 : V1.8.40
编译日期 : 2022-10-24
导致 lc2kicad-alpha-0.1.6 无法使用。

**Comment by chenhaimeng** [comment]
找到了一个方法，https://lceda.cn/ 这个网址进去选择标准版；
然后选择元件库，搜索，下载的格式可以是.json 格式；

**Comment by RigoLigoRLC** [comment]
只支持标准版的，用户需要自己判断使用的立创eda。
