### ISSUE TITLE
lc2kicad seems to fail if there are footprints imported to EasyEDA from AltiumDesigner

### ISSUE THREAD

**Issue by Cricko25** [RigoLigoRLC/LC2KiCad#7]
In case the file to be converted contains a footprint that was imported from AltiumDesigner, lc2kicad fails with messages like this:

Auto Parse Processor: Read file t2.json.                                                                                                                 
Auto Parse Processor: Document t2.json is a PCB file, exported by EasyEDA Editor 6.4.5.                                                                  terminate called after throwing an instance of 'std::invalid_argument'                                                                                   
  what():  stoi                                                                                                                                          
Aborted

The file containing only one component to reproduce the issue is attached.  Once again, with all other footprints (of what I have) everything seems to be fine, it only fails on footprints that were originally in AltiumDesigner; EasyEDA itself works with them having no problems.

[t2.json.gz](https://github.com/RigoLigoRLC/LC2KiCad/files/5201992/t2.json.gz)

**Comment by RigoLigoRLC** [comment]
![image](https://user-images.githubusercontent.com/49363666/92774000-a6c61280-f3cf-11ea-879f-b7f7d563c0c9.png)
This is because of the absence of "update time" field for footprints imported over from Altium. I've only worked with EasyEDA official footprints so didn't expect this.
