### ISSUE TITLE
On converting a footprint, parameter (net 0) is generated, which kicad doesn't understand

### ISSUE THREAD

**Issue by Cricko25** [RigoLigoRLC/LC2KiCad#9]
As a result of conversion of a file with a single footprint (which originally came from a kicad library) lc2kicad generates lines containing parameter (net 0), like this:

 (fp_line (start 44.230011 39.713002) (end 46.463001 37.480011) (width 0.098999) (layer F.Cu) (net 0))

The parameter (net 0) causes kicad to report an error; removing manually the (net 0) solves the problem.  The json file containing the only footprint that causes the problem is attached.

[test_json.zip](https://github.com/RigoLigoRLC/LC2KiCad/files/5350888/test_json.zip)

**Comment by RigoLigoRLC** [comment]
Woah, okay, I didn't expect this.
Generally KiCad doesn't support copper tracks in footprints, however EasyEDA does allow this. LC2KiCad did not handle this situation properly. My fault 😅 I'll see if I have time to commit a fix. Too busy recently
